sonar.organization=sylwekfr
sonar.projectKey=SylwekFr_SylwekFr.github.io
sonar.projectName=SylwekFr.github.io

onar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.test.ts,dist/**

sonar.sourceEncoding=UTF-8